services:
  postgres_control:
    image: postgres:16
    container_name: erp3d_postgres_control
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${CONTROL_DB_NAME}
      POSTGRES_USER: ${CONTROL_DB_USER}
      POSTGRES_PASSWORD: ${CONTROL_DB_PASSWORD}
    ports:
      - "${CONTROL_DB_PORT}:5432"
    volumes:
      - erp3d_pg_control_data:/var/lib/postgresql/data

volumes:
  erp3d_pg_control_data: